# Generated by Django 5.0.4 on 2024-04-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_video', models.FileField(upload_to='videoes/')),
            ],
        ),
    ]
